export const SET_ALGORITHM_INSERTION = 'SET_ALGORITHM_INSERTION';
export const SET_ALGORITHM_SELECTION = 'SET_ALGORITHM_SELECTION';
export const SET_ALGORITHM_BUBBLE = 'SET_ALGORITHM_BUBBLE';
export const SET_ALGORITHM_QUICK = 'SET_ALGORITHM_QUICK';
export const SET_ALGORITHM_MERGE = 'SET_ALGORITHM_MERGE';
export const SET_ORDER_ASCENDING = 'SET_ORDER_ASCENDING';
export const SET_ORDER_DESCENDING = 'SET_ORDER_DESCENDING';